server:
  host: 127.0.0.1
  username: Tp0t
  password: admin
  mail: tp0t_team@163.com
  port: 8080
  salt: "3916589616287113937"
  debug: false
email:
  host: smtp.163.com
  username: tp0t_team@163.com
  password: VHTPXZJYRYKGZBHA
challenge:
  secondBloodReward: 0.08
  thirdBloodReward: 0.05
  halfLife: 20
  firstBloodReward: 0.1
kubernetes:
  portAllocBegin: 30000
  portAllocEnd: 40000
  username: e3657677
  password: 5cfe939d
  registryHost: 110.40.152.78:5000