server:                              #平台服务器的配置参数
  host: 127.0.0.1                    #不用更改
  username: Tp0t                     #默认admin用户名
  password: admin                    #默认admin账号密码
  mail: admin@example.com            #默认admin账号邮箱
  port: 0                            #0时自动选择80/443，非0指定端口
  salt: "xxxxxxxxxx"                 #用于密码保护的salt，自动生成
  debug: false                       #无用参数
email:                               #邮件服务配置
  host: smtp.example.com             #邮件服务提供商服务器
  username: exampleUsername          #邮件发送账号
  password: examplePassword          #邮件发送账号密码（可能为授权码）
challenge:                           #题目分数控制参数
  firstBloodReward: 0.1              #一血分数奖励比例
  secondBloodReward: 0.08            #二血分数奖励比例
  thirdBloodReward: 0.05             #三血分数奖励比例
  halfLife: 20                       #题目分值减半所需解题人数
kubernetes:                          #k8s集群配置参数
  portAllocBegin: 30000              #自动分配端口范围起点
  portAllocEnd: 31000                #自动分配端口终点
  username: xxxxxxxx                 #「不可修改」镜像仓库用户名
  password: xxxxxxxx                 #「不可修改」镜像仓库密码
  registryHost: xxx.xxx.xxx.xxx:5000 #「不可修改」镜像仓库地址（与平台一致）
database:
  dsn: "host=localhost user=postgres password=admin dbname=oj port=5432 sslmode=disable TimeZone=Asia/Shanghai" # postgre dsn
  
