name: Tp0t_OJ

on:
  release:
    type: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: ">=16.14.0"

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in ~/.npm on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}-
           ${{ runner.os }}-build-
           ${{ runner.os }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
      name: List the state of node modules
      continue-on-error: true
      run: npm list


    - name: Prepare FrontEnd
      working-directory: ./app
      run: npm install

    - name: Build OJ
      working-directory: ./server
      run: go run build.go

    - name: Build Prepare
      working-directory: ./server
      run: go build prepare.go